"User Use cases": {
  shape: sequence_diagram
  user: {
    label: OciReader User
    shape: person
  }
  layer1: {
    label: Изглед
  }
  layer2: {
    label: Презентатор
  }
  layer3: {
    label: Модел
  }
  "Start program": {
    user.start -> layer1.start: Показване на библютеката\n
    layer1.start -> layer2.start: Извличане на книгите от библиотеката\n
    layer2.start -> layer3.start: Извличане на мета данни от базата дани на всички книги
    layer3.start -> layer2.start
    layer2.start.file_check -> layer2.start.file_check: Проверка на за наличност на файловете\n
    layer2.start -> layer1.start
    layer1.start.generate_view -> layer1.start.generate_view: Зареждане на върнатите данни в изгледа\n
    layer1.start -> user.start: Представяне на библиотеката\n
  }
}

